### ISSUE TITLE
Edit time and Save yields 405 - Method not allowed

### ISSUE THREAD

**Issue by jwwicks** [nicStuff/redmine_timesheet_extensions#14]
Steps to reproduce:
1. Install Redmine 1.1.2.stable.5268
2. Install latest Timesheet Extensions Plugin 0.1.0
3. Add an issue entry and update with log time
4. Click Timesheet menu item
5. List todays entries
6. Edit the entry in the list
7. Save the entry

This error (HTTP 405 Method Not Allowed) means that Internet Explorer was able to connect to the website, but the site has a programming error.

<pre>
Processing ApplicationController#index (for 74.93.20.89 at 2011-04-14 15:29:24) [POST]
  Parameters: {"time_entry"=>{"billed_hours"=>"", "comments"=>"Uploaded latest J1.5.23", "issue_id"=>"450", "end_minute"=>"30", "activity_id"=>"12", "start_hour"=>"11", "spent_on"=>"2011-04-13", "start_minute"=>"0", "hours"=>"0.5", "end_hour"=>"11"}, "back_url"=>"http%3A%2F%2Fdev.greatlittlebook.com%2Fcustom_timesheet%2Freport", "commit"=>"Save", "authenticity_token"=>"XXXXXXXXXXXXXX="}

ActionController::MethodNotAllowed (Only get requests are allowed.):
  /dh/passenger/lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  /dh/passenger/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:400:in `start_request_handler'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:351:in `handle_spawn_application'
  /dh/passenger/lib/phusion_passenger/utils.rb:184:in `safe_fork'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:349:in `handle_spawn_application'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:163:in `start'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:209:in `start'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'

</pre>

Happens in IE and FF.

Jw

**Comment by nicStuff** [comment]
Are you sure that you're using the plugin version compatible with redmine 1.1.x?

**Comment by jwwicks** [comment]
You can close this issue I unistalled and went back to using Eric's
timesheet. Still seeing the errors with the long urls for more than
10+ projects selected but I can live with that. Not as detailed as
yours but it works.

If my ruby programming was better I'd work on it myself but I just
don't have a ruby environment setup for debugging. Eclipse is setup
for PHP, Droid and C/C++. Sorry I can't be more helpful.

Jw

On Fri, May 20, 2011 at 11:58 PM, nicStuff
reply@reply.github.com
wrote:

> Are you sure that you're using the plugin version compatible with redmine 1.1.x?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nicStuff/redmine_timesheet_extensions/issues/14#comment_1213767

## 

John Wicks
Internet Application Developer
(916) 538-1857
jwwicks@gmail.com
http://jwwicks.com

A person who never made a mistake never tried anything new. - Albert Einstein

**Comment by nicStuff** [comment]
Ok, I'm sorry that I didn't provide a fix, but I'm happy that Eric's plugin is enough. Since it happens in Eric's original plugin doesn't mean that I have to close the issue, because it's anyway a challange...
Regards

nic

**Comment by jwwicks** [comment]
Yeah this particular error 405 doesn't appear in Eric's plugin when I
Save an edit, just the long url 406 one.

Jw

On Sat, May 21, 2011 at 12:39 AM, nicStuff
reply@reply.github.com
wrote:

> Ok, I'm sorry that I didn't provide a fix, but I'm happy that Eric's plugin is enough. Since it happens in Eric's original plugin doesn't mean that I have to close the issue, because it's anyway a challange...
> Regards
> 
> nic
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nicStuff/redmine_timesheet_extensions/issues/14#comment_1213856

## 

John Wicks
Internet Application Developer
(916) 538-1857
jwwicks@gmail.com
http://jwwicks.com

A person who never made a mistake never tried anything new. - Albert Einstein
