### ISSUE TITLE
Error: undefined method `billed_hours'

### ISSUE THREAD

**Issue by SeeDoubleYou** [nicStuff/redmine_timesheet_extensions#24]
When I install this plugin I run get an internal server error when trying to view a timesheet. The error log show the following, it seems something goes wrong with billed_hours:

```
ActionView::TemplateError (undefined method `billed_hours' for #<TimeEntry:0x7fca5c80d0f8>) on line #55 of vendor/plugins/redmine_timesheet_extensions/app/views/custom_timesheets/report.html.erb:
52:               <% end %>
53:               <%= table_col false, 'comments' do time_entry.comments end %>
54:               <%= table_col true, 'hours' do number_with_precision(time_entry.hours, :precision => @precision) end %>
55:               <%= table_col true, 'billed_hours' do '<strong>' + number_with_precision(time_entry.billed_hours, :precision => @precision) + '</strong>' unless time_entry.billed_hours.blank? end %>
56:               <% if selected?('id') %>
57:                 <td align="center">
58:                   <% if time_entry.editable_by?(User.current) -%>

/usr/lib/ruby/vendor_ruby/active_record/attribute_methods.rb:260:in `method_missing'
vendor/plugins/redmine_timesheet_extensions/app/views/custom_timesheets/report.html.erb:55
vendor/plugins/redmine_timesheet_extensions/app/helpers/custom_timesheets_helper.rb:122:in `table_col'
vendor/plugins/redmine_timesheet_extensions/app/views/custom_timesheets/report.html.erb:55
vendor/plugins/redmine_timesheet_extensions/app/views/custom_timesheets/report.html.erb:33:in `each'
vendor/plugins/redmine_timesheet_extensions/app/views/custom_timesheets/report.html.erb:33
/usr/lib/ruby/vendor_ruby/action_view/renderable.rb:34:in `send'
/usr/lib/ruby/vendor_ruby/action_view/renderable.rb:34:in `render'
/usr/lib/ruby/vendor_ruby/action_view/base.rb:306:in `with_template'
/usr/lib/ruby/vendor_ruby/action_view/renderable.rb:30:in `render'
/usr/lib/ruby/vendor_ruby/action_view/template.rb:205:in `render_template'
/usr/lib/ruby/vendor_ruby/action_view/base.rb:265:in `render'
/usr/lib/ruby/vendor_ruby/action_view/base.rb:348:in `_render_with_layout'
/usr/lib/ruby/vendor_ruby/action_view/base.rb:262:in `render'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:1252:in `render_for_file'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:942:in `render_without_benchmark'
/usr/lib/ruby/vendor_ruby/action_controller/benchmarking.rb:51:in `render'
/usr/lib/ruby/vendor_ruby/action_controller/benchmarking.rb:51:in `render'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:135:in `send'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:135:in `custom'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:179:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:179:in `respond'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:173:in `each'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:173:in `respond'
/usr/lib/ruby/vendor_ruby/action_controller/mime_responds.rb:107:in `respond_to'
vendor/plugins/redmine_timesheet_extensions/app/controllers/custom_timesheets_controller.rb:61:in `report'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:1333:in `send'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:1333:in `perform_action_without_filters'
/usr/lib/ruby/vendor_ruby/action_controller/filters.rb:617:in `call_filters'
/usr/lib/ruby/vendor_ruby/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/usr/lib/ruby/vendor_ruby/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/usr/lib/ruby/vendor_ruby/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/usr/lib/ruby/vendor_ruby/action_controller/rescue.rb:160:in `perform_action_without_flash'
/usr/lib/ruby/vendor_ruby/action_controller/flash.rb:151:in `perform_action'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:532:in `send'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:532:in `process_without_filters'
/usr/lib/ruby/vendor_ruby/action_controller/filters.rb:606:in `process'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:391:in `process'
/usr/lib/ruby/vendor_ruby/action_controller/base.rb:386:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/routing/route_set.rb:438:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/dispatcher.rb:87:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_controller/dispatcher.rb:121:in `_call'
/usr/lib/ruby/vendor_ruby/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:29:in `call'
/usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:29:in `call'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:9:in `cache'
/usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:28:in `call'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/string_coercion.rb:25:in `call'
/usr/lib/ruby/vendor_ruby/rack/head.rb:9:in `call'
/usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:24:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/params_parser.rb:15:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/session/cookie_store.rb:99:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/failsafe.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/rack/lock.rb:15:in `call'
/usr/lib/ruby/vendor_ruby/action_controller/dispatcher.rb:106:in `call'
/usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in `process_request'
/usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:374:in `start_request_handler'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:332:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:330:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:209:in `start'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/lib/phusion_passenger/passenger-spawn-server:61
```

**Comment by SeeDoubleYou** [comment]
Yes, so uh, forget this, it was my own dumb fault. The thing is I ran 
     rake db:migrate
instead of
     rake db:migrate_plugins

So now it all works as it should...
